version: '3.4'

services:
  db:
    image: postgres:13.3
    container_name: pg_container
    environment:
      POSTGRES_DB: rmoney_api_database
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: abc12345
    ports:
      - "5432:5432"