version: '3.4'

services:
  db:
    image: postgres:13.3
    container_name: pg_container
    command: wget https://github.com/harrybrar22/Rmoney_app/blob/main/database/data.sql -o ./database/data.sql
    environment:
      POSTGRES_DB: rmoney_api_database
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: abc12345
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"


  web:
    image: sidhubrar/rmoney_flask_app
    command: flask run --host 0.0.0.0
    volumes:
      - /code
    ports:
      - "5000:5000"
